apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.app1Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app1.service.name }}
                port:
                  number: {{ .Values.app1.service.port }}
          - path: {{ .Values.ingress.app2Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app2.service.name }}
                port:
                  number: {{ .Values.app2.service.port }}
