namespace: kabir

# First app (useless)
app1:
  name: useless
  image:
    repository: alok1408/fend
    tag: cp
  replicas: 2
  port: 80
  service:
    name: useless-svc
    type: ClusterIP
    port: 80
  strategy:
    maxSurge: 5
    maxUnavailable: 5

# Second app (useless-v2)
app2:
  name: useless-v2
  image:
    repository: pawanjadon/kabirepo
    tag: latest
  replicas: 2
  port: 80
  service:
    name: useless-v2-svc
    type: ClusterIP
    port: 80
  strategy:
    maxSurge: 5
    maxUnavailable: 5

# Ingress
ingress:
  name: nginx-ingress
  host: kabirpratap.sbs
  app1Path: /
  app2Path: /v2
